# Streamlit secrets for deployment
# Add your OpenAI API key here for production
# [secrets]
# openai_api_key = "your-openai-api-key-here"

# Or use environment variables in Streamlit Cloud:
# Go to your app settings and add:
# OPENAI_API_KEY = "your-openai-api-key-here"
